name: async_generator_builder
description: "A widget builder that takes Future and Stream generator."
version: 0.0.1
homepage: https://github.com/najeira/flutter_async_generator_builder

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
